load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mathutil",
    srcs = [
        "fibonacci.go",
        "mathutil.go",
    ],
    importpath = "bazel_polyglot_example/go/pkg/mathutil",
    visibility = ["//visibility:public"],
)

go_test(
    name = "mathutil_test",
    srcs = ["mathutil_test.go"],
    embed = [":mathutil"],
)
