load("@rules_scala//scala:scala.bzl", "scala_library")

package(default_visibility = ["//visibility:public"])

scala_library(
    name = "events",
    srcs = ["EventModel.scala"],
    deps = [
        "//scala/common/codec:codec",
        "//scala/common/time:time",
        "//scala/domain/contracts:contracts",
    ],
)
