load("@rules_scala//scala:scala.bzl", "scala_library")

package(default_visibility = ["//visibility:public"])

scala_library(
    name = "planner",
    srcs = ["PlanCompiler.scala"],
    deps = [
        "//scala/analysis/graph:graph",
        "//scala/common/time:time",
        "//scala/domain/contracts:contracts",
        "//scala/domain/events:events",
    ],
)
