load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "operations",
    srcs = ["operations.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "stats",
    srcs = ["stats.py"],
    deps = [":operations"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "mathutils",
    srcs = ["__init__.py"],
    deps = [
        ":operations",
        ":stats",
    ],
    visibility = ["//visibility:public"],
)
